---
  - name: Installation de Apache
    dnf:
     name: httpd
     state: present

  - name: Activation de Apache
    systemd:
     name: httpd
     state: started
     enabled: yes

  - name: Création des répertoires des sites
    file: 
     path: /var/www/{{ item }}
     state: directory
     mode: '0755'
     owner: root
     group: root
     recurse: yes
    loop:
     "{{ nom_sites }}"

  - name: Création des fichiers index.html a partir de modèles
    template:
     src: index.j2
     dest: /var/www/{{ item }}/html/index.html
    loop:
     "{{ nom_sites }}"

  - name: Création du template de fichier de conf
    template:
     src: conf.j2
     dest: /etc/httpd/conf.d/{{ item }}.conf
    loop:
     "{{ nom_sites }}"

  - name: Copier les fichiers php
    copy:
     src: php/
     dest: /var/www/{{ item }}/html/
    loop:
     "{{ nom_sites }}"
