---
  - name: installation Mariadb et package
    dnf:
     name: "{{ item }}"
     state: present
    loop:
     "{{ mariad_packages }}"
  - name:  Activation de Mariadb
    systemd:
     name: mariadb
     state: started
     enabled: yes
  - name: ajout .my.cnf conf mariadb
    copy:
     src: .my.cnf
     dest: /root/.my.cnf
