---
- name: Installation de php
  dnf:
   name: "{{ item }}"
   state: present
  loop:
   - php
   - php-fpm
   - php-pear
   - php-mbstring
- name: Restart Apache
  systemd:
   name: httpd
   state: restarted
